### ISSUE TITLE
switch to jdk 8 as compile platform breaks 1.7 compatibility

### ISSUE THREAD

**Issue by maksimlikharev** [Netflix/dyno#185]
Altho you have
 
sourceCompatibility = 1.7
targetCompatibility = 1.7

but it seems artifacts now compiled with java 8, that produce  this particular error when code run with java 7.

```
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at com.netflix.dyno.connectionpool.impl.hash.BinarySearchTokenMapper.initBinarySearch(BinarySearchTokenMapper.java:114)
	at com.netflix.dyno.connectionpool.impl.hash.BinarySearchTokenMapper.initSearchMecahnism(BinarySearchTokenMapper.java:78)
	at com.netflix.dyno.connectionpool.impl.lb.TokenAwareSelection.initWithHosts(TokenAwareSelection.java:66)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:348)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:627)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:526)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3521)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.createConnectionPool(DynoJedisClient.java:3509)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:3487)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3421)

``` 

if you continue to support 1.7, you have to compile with 1.7 jdk.

**Comment by ipapapa** [comment]
That is a good point. We have to fix that.

**Comment by ipapapa** [comment]
It has been addressed in #186.
